[api_keys]
cohere_api_key = "8jxJG3wg8U0VeHHqWTK7RBcKlnCEElt6iedi8wSn"
langchain_endpoint = "https://api.smith.langchain.com"
langchain_api_key = "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"
tavily_api_key = "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"
pinecone_api_key = "ce1cc817-16ac-4809-8d07-505080d79799"

[settings]
langchain_tracing_v2 = true